version: '3.9'

services:
  #  MySQL DB config
  spring-security-mysql:
    image: mysql:latest
    restart: always
    container_name: spring-security-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: spring-security
    ports:
      - "3306:3306"
    networks:
      - spring-security-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 1s
      timeout: 20s
      retries: 10

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    restart: always
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - spring-security-network
#    healthcheck:
#      test: [ "CMD","ping", "-h", "http://localhost:8761" ]
#      interval: 1s
#      timeout: 20s
#      retries: 10

  oauth-resource-server:
    #    image: neel0108p/oauth-resource-server
    build:
      context: ./oauth-resource-server
      dockerfile: Dockerfile
    restart: always
    container_name: oauth-resource-server
    depends_on:
      spring-security-mysql:
        condition: service_healthy
#      discovery-server:
#        condition: service_healthy
    links:
      - spring-security-mysql
      - discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://spring-security-mysql:3306/spring-security
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=test
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
    ports:
      - "8090:8090"
    networks:
      - spring-security-network

  oauth-client:
    #    image: neel0108p/oauth-client
    build:
      context: ./oauth-client
      dockerfile: Dockerfile
    restart: always
    container_name: oauth-client
    depends_on:
      spring-security-mysql:
        condition: service_healthy
#      discovery-server:
#        condition: service_healthy
    links:
      - spring-security-mysql
      - discovery-server
      - oauth-resource-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://spring-security-mysql:3306/spring-security
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=test
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - spring-security-network

networks:
  spring-security-network:
    driver: bridge

