spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  instance:
    hostname: discovery-server
  server:
    responseCacheUpdateIntervalMs: 500
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
