server:
  port: 8080

spring:
  application:
    name: oauth-client
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          okta:
            provider: spring
            client-id: 0oaf0ow40uUMcVVgv5d7
            client-secret: U9Ev8IH2-T3ukJ698-WqarqLq6S-8toAmG0RkLbVbXTVAoLReTPlogW9f2-J5-8L
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, api.read
        provider:
          spring:
            issuer-uri: https://dev-22461297.okta.com/oauth2/default

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

eureka:
  instance:
    hostname: oauth-client
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  client:
    registryFetchIntervalSeconds: 2
    serviceUrl:
      defaultZone=${EUREKA_SERVER:http://discovery-server/eureka/}:

resource-server:
  api-url-value: oauth-resource-server

okta:
  domain-url: https://dev-22461297.okta.com
  api-token: 00rieZ5ksXHOVvb3-D1PmON40qYuYhwRgVt7vFyEMb
